### ISSUE TITLE
Autocomplete component name in .vue template  (using element plus + Pug)

### ISSUE THREAD

**Issue by orenmizr** [antfu/unplugin-vue-components#149]
_i am using vite + element plus + auto components + auto imports + pug as template... amazing setup thanks to antfu._ 

is there a setting out there that can provide auto completion for components of the loaded lib ? - for element-plus el-b... would autocomplete button etc

**Comment by antfu** [comment]
If you have the component imported once with `dts` flag enabled. You should get the auto-complete work out-of-box with Volar. Since the components are resolved on-demanded, currently there is no such way to list all the possibilities (you might need some framework to specify auto-complete support then Volar).

**Comment by orenmizr** [comment]
I have volar installed. I see the component listed as I did enabled
typescript. Perhaps it is because I'm using a pug template  ?
