### ISSUE TITLE
New components aren’t picked up automatically?

### ISSUE THREAD

**Issue by LeBenLeBen** [antfu/unplugin-vue-components#16]
When I create a new component in `src/components` and right after reference it in another one, I get an error saying the component could not be resolved. I have to restart Vite for the component to be available.

Is this the desired behavior because of some limitations or am I doing something wrong?

**Comment by antfu** [comment]
There is definitely some HMR support need to be improved since the changes for Vite 2.

Need to add a file watcher hook to update the components map. If you are interested in it, feel free to give it a try and draft a PR, and let me know if you have any further questions. (or I will do it later anyway, but won't be too soon). Thank you.

**Comment by HomyeeKing** [comment]
I don't encounter this kind of issue, but the cache after delete the target component
after I delete the component, it still stay on the page even refresh the page
is this expected?

**Comment by mohannad-musleh** [comment]
@LeBenLeBen i have the same issue, and i found a temporary solution

i implemented the `importPathTransform` function that fix the invalid paths

```js
ViteComponents({
  dirs: ['components'],
  deep: true,
  extensions: ['vue'],
  importPathTransform: path => {
    if(path.startsWith('/../../components')) {
      return path.replace('/../../components', '/components');
    }
    return path;
  },
})
```

**Comment by antfu** [comment]
I believe this is already fixed.
